FROM paf-dependencies

WORKDIR /pafinder
#RUN git clone https://github.com/mmalenta/PAFINDER.git --branch gpu_send --single-branch ./
#RUN git clone https://github.com/astrooman/paf.git --branch cleanup --single-branch ./
#RUN git clone https://github.com/astrooman/paf.git --branch test --single-branch ./
RUN git clone https://github.com/astrooman/paf.git --branch scale --single-branch ./
#RUN git clone https://github.com/astrooman/paf.git --branch effelsberg_working --single-branch ./

RUN mkdir obj && \
    mkdir bin && \
    touch Makefile.inc && \
    echo "SRC_DIR=./src" >> Makefile.inc && \
    echo "INC_DIR=./include" >> Makefile.inc && \
    echo "OBJ_DIR=./obj" >> Makefile.inc && \
    echo "BIN_DIR=./bin" >> Makefile.inc && \
    echo "DEDISP_DIR=./dedisp_paf" >> Makefile.inc && \
    echo "CC=g++" >> Makefile.inc && \
    echo "NVCC=$(which nvcc)" >> Makefile.inc && \
    make && \
    echo "IPS 10.17.8.1" >> config.conf && \
    echo "GPUIDS 0" >> config.conf && \
    echo "RA 0.0" >> config.conf && \
    echo "DEC 0.0" >> config.conf && \
    echo "BEAM 0" >> config.conf && \
    g++ ./tools/net_test.cpp -o ./tools/net_test -std=c++11 -lpthread  && \ 
    echo "set nocompatible" >> ~/.vimrc && \
    echo "set backspace=2" >> ~/.vimrc

ENV PATH ${PATH}:/paf/bin
WORKDIR /
