FROM paf-dependencies

WORKDIR /

RUN git clone https://git.code.sf.net/p/heimdall-astro/code heimdall
WORKDIR /heimdall
RUN ./bootstrap && \
    ./configure --prefix=/heimdall-install/ --with-dedisp-include-dir=/dedisp/src/ --with-cuda-dir=/usr/local/cuda-8.0 --with-psrdada-include-dir=/psrdada-install/include/ && \
    make && \
    make install

